apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "amravazzi/study-kubernetes:v5.8"

          resources:
            requests: # minimum app specs which is reserved by k8s
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          ports:
          - name: liveness-port
            containerPort: 8000

          startupProbe:
            httpGet:
              path: /healthz # endpoint
              port: liveness-port # container port
            periodSeconds: 3 # seconds per request
            failureThreshold: 10 # failure limit threshold

          readinessProbe:
            httpGet:
              path: /healthz # endpoint
              port: liveness-port # container port
            periodSeconds: 3 # seconds per request
            failureThreshold: 1 # failure limit threshold

          livenessProbe:
            httpGet:
              path: /healthz # endpoint
              port: liveness-port # container port
            periodSeconds: 5 # seconds per request
            failureThreshold: 1 # failure limit threshold
            timeoutSeconds: 1
            successThreshold: 1 # how many 200 to say the pod is ok

          envFrom:
            # - configMapRef:
            #     name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - name: config
              mountPath: "/go/myfamily"
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: family.txt
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE