apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  goserver
  labels:
    app: goserver
spec:
  # filter
  selector:
    matchLabels:
      app: goserver
  replicas: 10
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "amravazzi/study-kubernetes:latest"